name: Tests

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0' ]

      fail-fast: false

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: soap

      - run: composer install --no-progress --prefer-dist
      - run: vendor/bin/tester tests -s -C
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: tests/**/output


  lowest_dependencies:
    name: Lowest Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          extensions: soap

      - run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
      - run: vendor/bin/nunjuck -s -c ./tests/php.ini ./tests


  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          extensions: soap, phpdbg

      - run: composer install --no-progress --prefer-dist
      - run: composer coverage
      - run: wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      - run: php coveralls.phar --verbose --config tests/.coveralls.yml